---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tf-controller-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://weaveworks.github.io/tf-controller