---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: tf-controller
      version: 0.9.7
      sourceRef:
        kind: HelmRepository
        name: tf-controller-charts
        namespace: flux-system
  values:
    installCRDs: false

